//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KY.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KY.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not resolve dependency {0}.
        /// </summary>
        public static string CanNotResolveDependency {
            get {
                return ResourceManager.GetString("CanNotResolveDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd.MM.yyyy HH:mm:ss.fff}: {1} occurred. {2}.
        /// </summary>
        public static string ConsoleErrorFormat {
            get {
                return ResourceManager.GetString("ConsoleErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd.MM.yyyy HH:mm:ss.fff}: {1}.
        /// </summary>
        public static string ConsoleTraceFormat {
            get {
                return ResourceManager.GetString("ConsoleTraceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not log empty exception.
        /// </summary>
        public static string EmptyException {
            get {
                return ResourceManager.GetString("EmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not be empty.
        /// </summary>
        public static string ErrorCanNotBeEmpty {
            get {
                return ResourceManager.GetString("ErrorCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1:MM.dd}.log.
        /// </summary>
        public static string FileCustomFileName {
            get {
                return ResourceManager.GetString("FileCustomFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.{0:MM.dd}.log.
        /// </summary>
        public static string FileErrorFileName {
            get {
                return ResourceManager.GetString("FileErrorFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ================================================
        ///{0:dd.MM.yyyy HH:mm:ss.fff}: {1} occured
        ///{2}
        ///.
        /// </summary>
        public static string FileErrorFormat {
            get {
                return ResourceManager.GetString("FileErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trace.{0:MM.dd}.log.
        /// </summary>
        public static string FileTraceFileName {
            get {
                return ResourceManager.GetString("FileTraceFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:dd.MM.yyyy HH:mm:ss.fff}: {2}
        ///.
        /// </summary>
        public static string FileTraceFormat {
            get {
                return ResourceManager.GetString("FileTraceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-Exception. Logging failed.\n\n{1}.
        /// </summary>
        public static string LoggingFailedMessage {
            get {
                return ResourceManager.GetString("LoggingFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ungültige Domain. War {0} gemeint?.
        /// </summary>
        public static string MailAdressInvalidDomain {
            get {
                return ResourceManager.GetString("MailAdressInvalidDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nicht vertrauenswürdige Top-Level-Domain.
        /// </summary>
        public static string MailAdressUntrustedTopLevelDomain {
            get {
                return ResourceManager.GetString("MailAdressUntrustedTopLevelDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0} occurred. {1}.
        /// </summary>
        public static string MsBuildErrorFormat {
            get {
                return ResourceManager.GetString("MsBuildErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string MsBuildErrorShortFormat {
            get {
                return ResourceManager.GetString("MsBuildErrorShortFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string MsBuildTraceFormat {
            get {
                return ResourceManager.GetString("MsBuildTraceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: {0}.
        /// </summary>
        public static string MsBuildWarningFormat {
            get {
                return ResourceManager.GetString("MsBuildWarningFormat", resourceCulture);
            }
        }
    }
}
